name: Continuous Integration
on: [ push, pull_request ]
jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP, with composer and extensions
                uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
                with:
                    php-version: '8.0'
                    coverage: xdebug
            -   name: Install Composer dependencies
                run: |
                    composer self-update --no-interaction
                    composer update --no-interaction --prefer-dist --optimize-autoloader
            -   name: Run CI Commands
                run: |
                    composer ci-run
